### ISSUE TITLE
Unsupported operand type

### ISSUE THREAD

**Issue by ImaFruitSnack** [dwalone/Latex2Python#4]
Traceback (most recent call last):
  File "/home/runner/tbc/Latex2Python/latex2python.py", line 183, in <module>
    main()
  File "/home/runner/tbc/Latex2Python/latex2python.py", line 168, in main
    s = repFunctions(f, s)  
  File "/home/runner/tbc/Latex2Python/latex2python.py", line 79, in repFunctions
    s = s[:i] + '(' + s_strip1[:pos1+1] + '/' + s_strip2[:pos2+1] + ')' + s_strip2[pos2+1:]  
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by dwalone** [comment]
What was the latex string you were trying to convert?
